--FILE 5
CREATE VIEW SUPPLER_INVOICE_PAYMENT AS
SELECT S.SUP_ID, I.INVOICE_ID, P.PAYM_ID
FROM SUPPLIER S
JOIN INVOICE I 
ON S.SUP_ID = I.SUP_ID AND S.SUP_LICENSENUMBER = I.SUP_LICENSENUMBER
JOIN PAYMENT P
ON S.SUP_ID = P.SUP_ID AND S.SUP_LICENSENUMBER = P.SUP_LICENSENUMBER
WHERE I.INVOICE_CURRENCY = 'MYR';
SELECT * FROM SUPPLER_INVOICE_PAYMENT;
