--FILE 3
SET LINESIZE 200
SET PAGESIZE 50
SET WRAP OFF
SET TRIMSPOOL ON

COLUMN CLINIC_ADDRESS FORMAT A30
COLUMN CLINIC_CITY FORMAT A15
COLUMN SERV_SAFETYEQUIPMENT FORMAT A25
COLUMN SERV_RETURNSTATUS FORMAT A10
COLUMN CONT_EMAIL FORMAT A25
COLUMN CONT_PHONENUMBERTYPE FORMAT A10
COLUMN ROOM_NAME FORMAT A15
COLUMN ROOM_AVAILABILITYSTATUS FORMAT A12
COLUMN INV_CONDITIONSTATUS FORMAT A10
COLUMN INV_ITEMORIGIN FORMAT A10
COLUMN DEV_FEE FORMAT 9999
COLUMN DEV_RISKLEVEL FORMAT A5
COLUMN TOTALROWS FORMAT 999

SELECT
CB.CLINIC_ADDRESS, CB.CLINIC_CITY,
AMB.SERV_SAFETYEQUIPMENT, AMB.SERV_RETURNSTATUS,
C.CONT_EMAIL, C.CONT_PHONENUMBERTYPE,
R.ROOM_NAME, R.ROOM_AVAILABILITYSTATUS,
I.INV_CONDITIONSTATUS, I.INV_ITEMORIGIN,
MD.DEV_FEE, MD.DEV_RISKLEVEL,
COUNT(*) OVER () AS TotalRows
FROM CLINIC_BRANCH CB
JOIN AMBULANCE_SERVICE AMB
ON CB.CLINIC_ID = AMB.CLINIC_ID AND CB.CLINIC_REGISTRATIONNUMBER = AMB.CLINIC_REGISTRATIONNUMBER
JOIN AMBULANCE_SERVICE_MEDICAL_DEVICE ASMD
ON AMB.SERV_ID = ASMD.SERV_ID AND AMB.SERV_REQUESTID = ASMD.SERV_REQUESTID
JOIN CONTACT C
ON CB.CLINIC_ID = C.CLINIC_ID AND CB.CLINIC_REGISTRATIONNUMBER = C.CLINIC_REGISTRATIONNUMBER
JOIN ROOM R
ON CB.CLINIC_ID = R.CLINIC_ID AND CB.CLINIC_REGISTRATIONNUMBER = R.CLINIC_REGISTRATIONNUMBER
JOIN INVENTORY_ROOM IR
ON R.ROOM_ID = IR.ROOM_ID AND R.ROOM_NUMBER = IR.ROOM_NUMBER
JOIN INVENTORY I
ON IR.INV_ID = I.INV_ID AND IR.INV_SERIALTRACKED = I.INV_SERIALTRACKED
JOIN MEDICAL_DEVICE MD
ON I.INV_ID = MD.INV_ID AND I.INV_SERIALTRACKED = MD.INV_SERIALTRACKED AND ASMD.DEV_ID = MD.DEV_ID AND ASMD.DEV_SERIALNUMBER = MD.DEV_SERIALNUMBER
WHERE CB.CLINIC_TOTALSTAFF > 20 AND MD.DEV_RISKLEVEL = 'Low' AND AMB.SERV_RETURNSTATUS = 'Completed';




