--FILE 2
SELECT 
    D.DOC_ID, 
    SUM(S.SALARY_MONTHLY) AS TotalSalary,  -- Aggregation to sum the monthly salary for each doctor
    WS.SCHED_DAYASSIGNED,
    COUNT(LD.LEAVE_REASON) AS TotalLeaveDays  -- Aggregation to count the number of leave days for each doctor
FROM 
    DOCTOR D
JOIN 
    SALARY S
    ON D.DOC_ID = S.DOC_ID 
    AND D.DOC_OWNER = S.DOC_OWNER 
    AND D.DOC_LICENSENUMBER = S.DOC_LICENSENUMBER
JOIN 
    WORK_SCHEDULE WS
    ON S.SALARY_ID = WS.SALARY_ID 
    AND S.SALARY_ACCOUNTNUMBER = WS.SALARY_ACCOUNTNUMBER 
    AND D.DOC_ID = WS.DOC_ID 
    AND D.DOC_OWNER = WS.DOC_OWNER 
    AND D.DOC_LICENSENUMBER = WS.DOC_LICENSENUMBER
JOIN 
    LEAVE_DAY_DOCTOR LVD
    ON D.DOC_ID = LVD.DOC_ID 
    AND D.DOC_OWNER = LVD.DOC_OWNER 
    AND D.DOC_LICENSENUMBER = LVD.DOC_LICENSENUMBER
JOIN 
    LEAVE_DAY LD
    ON S.SALARY_ID = LD.SALARY_ID 
    AND S.SALARY_ACCOUNTNUMBER = LD.SALARY_ACCOUNTNUMBER 
    AND LVD.LEAVE_ID = LD.LEAVE_ID 
    AND LVD.LEAVE_REFERENCENUMBER = LD.LEAVE_REFERENCENUMBER
WHERE 
    D.DOC_OWNER = 'No' 
    AND S.SALARY_BONUSAMOUNT > 100
GROUP BY 
    D.DOC_ID, WS.SCHED_DAYASSIGNED;