--FILE 4
SELECT R.ROOM_NUMBER, P.PATIENT_ID, A.APP_REASON, C.CONS_SESSIONID, MR.RECORD_DIAGNOSIS,
PRES.PRES_NOTES, CB.CLINIC_ADDRESS, CONT.CONT_EMAIL
FROM ROOM R
JOIN PERSON_ROOM PR
ON R.ROOM_ID = PR.ROOM_ID AND R.ROOM_NUMBER = PR.ROOM_NUMBER
JOIN PATIENT P
ON PR.P_FULLNAME = P.P_FULLNAME AND PR.P_ICNUMBER = P.P_ICNUMBER
JOIN APPOINTMENT A
ON R.ROOM_ID = A.ROOM_ID AND R.ROOM_NUMBER = A.ROOM_NUMBER
JOIN CONSULTATION C
ON C.CONS_ID = A.CONS_ID AND C.CONS_SESSIONID = A.CONS_SESSIONID
JOIN MEDICAL_RECORD MR
ON MR.RECORD_ID = C.RECORD_ID AND MR.RECORD_FILECODE = C.RECORD_FILECODE
JOIN PRESCRIPTION PRES
ON C.CONS_ID = PRES.CONS_ID AND C.CONS_SESSIONID = PRES.CONS_SESSIONID
JOIN CLINIC_BRANCH CB
ON CB.CLINIC_ID = R.CLINIC_ID AND CB.CLINIC_REGISTRATIONNUMBER = R.CLINIC_REGISTRATIONNUMBER
JOIN CONTACT CONT
ON CB.CLINIC_ID = CONT.CLINIC_ID AND CB.CLINIC_REGISTRATIONNUMBER = CONT.CLINIC_REGISTRATIONNUMBER
JOIN PERSON_CONTACT PC
ON CONT.CONT_ID = PC.CONT_ID AND CONT.CONT_PHONENUMBER = PC.CONT_PHONENUMBER AND PR.P_FULLNAME = PC.P_FULLNAME AND PR.P_ICNUMBER = PC.P_ICNUMBER
WHERE R.ROOM_AVAILABILITYSTATUS = 'Available' AND CB.CLINIC_OPERATINGHOURS = '9am - 6pm' AND CONT.CONT_PREFERREDMETHOD = 'Phone' AND P.PATIENT_BLOODTYPE = 'A+'
ORDER BY P.PATIENT_ID DESC;
